version: '3.2'
services:

  microservice-postgres:
    container_name: microservice-postgres
    image: "postgres:14-alpine"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: service-test
      POSTGRES_DB: service-test
      POSTGRES_USER: service-test
    volumes:
      - .:/code
    networks:
      - net


  microservice-pgadmin:
    container_name: microservice-pgadmin
    image: "dpage/pgadmin4"
    ports:
      - "5050:5050"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - net
    depends_on:
      - database

  microservice:
    container_name: intent-detector-service
    image: intent-detector-service
    build:
      context: .
    environment:
      ALLOW_ORIGINS: ".*"
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - net
    depends_on:
      - database


networks:
  net:
    ipam:
      config:
        - subnet: 192.168.168.0/24
