version: '3.2'
services:

  {{cookiecutter.project_name}}-postgres-db:
    container_name: {{cookiecutter.project_name}}-postgres-db
    image: "postgres:14-alpine"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: service-test
      POSTGRES_DB: service-test
      POSTGRES_USER: service-test
    volumes:
      - .:/code
    networks:
      - net


  {{cookiecutter.project_name}}-pgadmin:
    container_name: {{cookiecutter.project_name}}-pgadmin
    image: "dpage/pgadmin4"
    ports:
      - "5050:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - net
    depends_on:
      - {{cookiecutter.project_name}}-postgres-db

#  {{cookiecutter.project_name}}-web:
#    container_name: {{cookiecutter.project_name}}-web
#    image: {{cookiecutter.project_name}}
#    build:
#      context: .
#    environment:
#      ALLOW_ORIGINS: ".*"
#      DB_HOST: {{cookiecutter.project_name}}-postgres-db
#      DB_PORT: "5432"
#    env_file:
#      - .env
#    ports:
#      - "8000:8000"
#    networks:
#      - net
#    depends_on:
#      - {{cookiecutter.project_name}}-postgres-db


networks:
  net:
    ipam:
      config:
        - subnet: 192.168.168.0/24
