name: ci

on:
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*' # don't run ci on tags, should already have run on commit tag points to.
    paths-ignore:
      - README.md
      - dev.md
  pull_request:
    branches:
      - 'dependabot*'
  schedule:
    - cron: '0 0 * * 1' # Every monday at midnight

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Setup BATS
      uses: mig4/setup-bats@v1
      with:
        bats-version: 1.2.1
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install python packages
      run: |
        poetry install
    - name: Test
      run: |
        # bats -r does not follow symlinks, pass paths explicitly using find
        # test_helper.bash setUp function handles creating the project under test using cookiecutter
        bats $(find ./tests -name '*.bats' | sort)